### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by alexanderadam** [ylc395/joplin-plugin-better-markdown-viewer#6]
I was wondering why Joplin blocks port `3000` and it seems that [I'm not the only one](https://discourse.joplinapp.org/t/why-does-joplin-open-port-3000/29468/5).

It would be nice to change the default since port `3000` is pretty popular and maybe even making the port configurable?

**Comment by ylc395** [comment]
2.1.0 is published. You can change the port this plugin use.

**Comment by alexanderadam** [comment]
Nice, wonderful! Thank you!
